[mypy]
strict = False
exclude = (build|dist|setup.py|.venv)

check_untyped_defs = True

ignore_missing_imports = False

python_version = 3.11

[mypy-nilearn.image]
ignore_missing_imports = True
[mypy-nipype]
ignore_missing_imports = True
[mypy-scipy.*]
ignore_missing_imports = True
[mypy-templateflow.*]
ignore_missing_imports = True

