# -*- coding: utf-8 -*-
# emacs: -*- mode: python; py-indent-offset: 4; indent-tabs-mode: nil -*-
# vi: set ft=python sts=4 ts=4 sw=4 et:

from multiprocessing import cpu_count
from operator import attrgetter
from pathlib import Path
import re
from subprocess import check_call
from tempfile import mkdtemp
from typing import Any

import nibabel as nib
import numpy as np
from docx import Document
from halfpipe import resource as hr
from halfpipe.interfaces.image_maths.resample import Resample
from nilearn.image import new_img_like
import pandas as pd

from . import __version__
from .merge import AtlasMerge

temporary_path = Path(mkdtemp())

neuromark_atlas = "Neuromark_fMRI_1.0.nii"
neuromark_atlas_url = f"https://github.com/trendscenter/gift/raw/master/GroupICAT/icatb/icatb_templates/{neuromark_atlas}"
neuromark_labels = "Neuromark_fMRI_1.0_Labels.doc"
neuromark_labels_url = (
    f"https://trendscenter.org/trends/data/neuromark/{neuromark_labels}"
)

extra_resources = dict()
extra_resources[neuromark_atlas] = neuromark_atlas_url
extra_resources[neuromark_labels] = neuromark_labels_url

hr.online_resources.update(extra_resources)

out_prefix = "atlas-NeuroMark_probseg"


def build() -> None:
    check_call(
        ["soffice", "--convert-to", "docx", hr.get(neuromark_labels)], cwd=temporary_path
    )
    labels_path = temporary_path / neuromark_labels.replace(".doc", ".docx")

    document = Document(str(labels_path))

    pattern = re.compile(r"(.+) \((.+)\)")

    (table,) = document.tables
    column = table.columns[0]

    network_name: str | None = None
    network_short_name: str | None = None

    records: list[dict[str, Any]] = list()

    for text in map(attrgetter("text"), column.cells):
        match = pattern.fullmatch(text)
        if match is None:
            continue

        short_name: str | None = None
        index: int | None = None

        name, extra = match.groups()
        if "," in extra:
            short_name, extra = extra.split(",")
        extra = extra.strip()
        if extra.isdigit():
            index = int(extra)
        else:
            short_name = extra
        if short_name is not None:
            short_name = re.sub(r"[\[\]\s]", "", short_name)

        if index is None:
            network_name = name
            network_short_name = short_name
        else:
            records.append(
                dict(
                    index=index,
                    name=name,
                    short_name=short_name,
                    network_name=network_name,
                    network_short_name=network_short_name,
                )
            )

    pd.DataFrame.from_records(records).replace(
        to_replace=[None], value=pd.NA
    ).set_index("index").to_csv(f"{out_prefix}.tsv", sep="\t")

    merge = AtlasMerge()

    atlas_path = hr.get(neuromark_atlas)

    interface = Resample(
        input_image=str(atlas_path),
        input_space="MNI152NLin6Asym",
        reference_space=merge.template,
        reference_res=merge.resolution,
        float=False,
        interpolation="LanczosWindowedSinc",
        num_threads=cpu_count(),
    )
    result = interface.run()

    atlas_img = nib.nifti1.load(result.outputs.output_image)
    atlas = atlas_img.get_fdata()

    out_atlas_img = new_img_like(merge.fixed_img, atlas, copy_header=True)
    out_atlas_img.header["descrip"] = (
        f"Generated by HALFpipe/Atlases version {__version__}"
    )
    out_atlas_img.header.set_data_dtype(np.float64)

    nib.save(out_atlas_img, f"{out_prefix}.nii.gz")

    # Clean up temporary file.
    Path(result.outputs.output_image).unlink()


if __name__ == "__main__":
    build()
