name: continuous integration

on:
  push:
    branches: 
      - main 
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    container: ghcr.io/halfpipe/halfpipe:latest

    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache data
        uses: actions/cache@v2
        with:
          path: /home
          key: ${{ runner.os }}-home

      - name: Install FreeSurfer license file
        shell: bash
        env:
          FREESURFER_LICENSE_BASE64: "bGVhLndhbGxlckBjaGFyaXRlLmRlCjI3OTk5CiAqQ2R5NnNBR1BoQWlrCiBGU2t2cmduNFc0UXhRCg=="
        run: |
          echo ${FREESURFER_LICENSE_BASE64} | base64 --decode > ${FREESURFER_HOME}/license.txt

      - name: Install dependencies
        shell: bash
        run: |
          apt update
          apt install -y zip
          pip install --upgrade pip
          pip install .

      - name: Build atlases
        run: |
          ATLAS_DIR=/tmp/atlases
          mkdir -p ${ATLAS_DIR}
          cd ${ATLAS_DIR}
          halfpipe-atlases-build
          zip /tmp/atlases.zip *

      - name: Upload atlases
        uses: actions/upload-artifact@v2
        with:
          name: atlases.zip
          path: /tmp/atlases.zip
