name: continuous integration

on:
  push:
    branches: 
      - main 
    tags:
      - "*.*.*"  # Any tag that looks like a version
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup container
        run: |
          echo $GITHUB_OUTPUT
          docker run \
            --detach \
            --rm \
            --name="build" \
            --volume="/home/runner:/home/runner" \
            --volume="$(pwd):/halfpipe" \
            --workdir="/halfpipe" \
            --entrypoint="tail" \
            ${{ secrets.REGISTRY }}/halfpipe \
            --follow /dev/null

      - name: Install dependencies
        shell: docker exec build bash -x -e {0}
        run: |
          apt-get --yes update
          apt-get --yes install libreoffice git zip

      - name: Build atlases
        id: build_atlases
        shell: docker exec build bash -x -e {0}
        run: |
          echo $GITHUB_OUTPUT
          cat > "${FREESURFER_HOME}/license.txt" <<EOF
          halfpipe@fmri.science
          73053
           *C8FMo8yrzcZA
           FSCA7.lDgNIow
           e1n3o06osRFD3qtBRgsTy9f9bQHGOpY/riIUrHoEx5c=
          EOF

          pip install --verbose .

          atlas_dir=atlases
          mkdir ${atlas_dir}
          pushd ${atlas_dir} || exit

          halfpipe-atlases-build
          
          zip_path=atlases.zip
          zip ${zip_path} *

          echo "zip_path=${zip_path}" >> "${GITHUB_OUTPUT}"

      - name: Stop container
        run: |
          docker kill build

      - name: Upload atlases
        uses: actions/upload-artifact@v4
        with:
          name: atlases.zip
          path: ${{ steps.build_atlases.outputs.zip_path }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.build_atlases.outputs.zip_path }}
