name: continuous integration

on:
  push:
    branches: 
      - master 
  pull_request:
    branches: 
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    # Docker Hub image that `container-job` executes in
    # Use latest
    container: ghcr.io/halfpipe/halfpipe:latest

    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache data
        uses: actions/cache@v2
        with:
          path: /home
          key: ${{ runner.os }}-home

      - name: Install dependencies
        shell: bash
        run: |
          apt update
          apt install -y zip
          python -m pip install --upgrade pip
          pip install .

      - name: Build atlases
        run: |
          ATLAS_DIR=/tmp/atlases
          mkdir -p ${ATLAS_DIR}
          cd ${ATLAS_DIR}
          halfpipe-atlases-build
          zip /tmp/atlases.zip *

      - name: Upload atlases
        uses: actions/upload-artifact@v2
        with:
          name: atlases.zip
          path: /tmp/atlases.zip
