on:
  push:
    tags:
      - "*.*.*"  # Any tag that looks like a version

name: release

jobs:
  build:
    runs-on: ubuntu-latest

    container: ghcr.io/halfpipe/halfpipe:latest
  
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache data
        uses: actions/cache@v2
        with:
          path: /home
          key: ${{ runner.os }}-home

      - name: Install FreeSurfer license file
        shell: bash
        env:
          FREESURFER_LICENSE_BASE64: "bGVhLndhbGxlckBjaGFyaXRlLmRlCjI3OTk5CiAqQ2R5NnNBR1BoQWlrCiBGU2t2cmduNFc0UXhRCg=="
        run: |
          echo ${FREESURFER_LICENSE_BASE64} | base64 --decode > ${FREESURFER_HOME}/license.txt

      - name: Install dependencies
        shell: bash
        run: |
          apt update
          apt install -y zip
          pip install --upgrade pip
          pip install .
          conda install -c conda-forge -y hub

      - name: Build atlases
        id: build_atlases
        shell: bash
        run: |
          set -x

          output_path=/tmp/halfpipe-atlases
          mkdir -p ${output_path}
          cd ${output_path}
          halfpipe-atlases-build

          zip_path=${output_path}.zip
          zip ${zip_path} *

          echo "::set-output name=zip_path::${zip_path}"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.build_atlases.outputs.zip_path }}
