on:
  push:
    tags:
      - "*.*.*"  # Any tag that looks like a version

name: release

jobs:
  build:
    runs-on: ubuntu-latest

    # Docker Hub image that `container-job` executes in
    # Use latest
    container: ghcr.io/halfpipe/halfpipe:latest
  
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache data
        uses: actions/cache@v2
        with:
          path: /home
          key: ${{ runner.os }}-home

      - name: Install FreeSurfer license file
        shell: bash
        env:
          FREESURFER_LICENSE_BASE64: "bGVhLndhbGxlckBjaGFyaXRlLmRlCjI3OTk5CiAqQ2R5NnNBR1BoQWlrCiBGU2t2cmduNFc0UXhRCg=="
        run: |
          echo ${FREESURFER_LICENSE_BASE64} | base64 --decode > ${FREESURFER_HOME}/license.txt

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Build atlases
        id: build_atlases
        run: |
          set -x
          ATLAS_DIR=/tmp/atlases
          mkdir -p ${ATLAS_DIR}
          cd ${ATLAS_DIR}
          halfpipe-atlases-build
          echo "::set-output name=atlas_dir::${ATLAS_DIR}"

      - name: Create release
        env:
          ATLAS_DIR: ${{ steps.build_atlases.outputs.atlas_dir }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
        run: |
          set -x
          ASSETS=()
          for ASSET in ${ATLAS_DIR}/*; do
            ASSETS+=("-a" "${ASSET}")
          done
          hub release create "${ASSETS[*]}" -m "Release ${GITHUB_REF}" "${GITHUB_REF}"
