on:
  push:
    tags:
      - "*.*.*"  # Any tag that looks like a version

name: release

jobs:
  build:
    runs-on: self-hosted
    container: ghcr.io/halfpipe/halfpipe:latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build atlases
        id: build_atlases
        shell: bash
        run: |
          set -x
            
          mamba install -y zip

          freesurfer_license_base64="bGVhLndhbGxlckBjaGFyaXRlLmRlCjI3OTk5CiAqQ2R5NnNBR1BoQWlrCiBGU2t2cmduNFc0UXhRCg=="
          echo ${freesurfer_license_base64} \
            | base64 --decode > ${FREESURFER_HOME}/license.txt

          pip install --verbose .

          atlas_dir=/tmp/atlases
          mkdir -p ${atlas_dir}
          cd ${atlas_dir}

          halfpipe-atlases-build
          
          zip_path=${atlas_dir}.zip
          zip ${zip_path} *

          echo "zip_path=${zip_path}" >> ${GITHUB_OUTPUT}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.build_atlases.outputs.zip_path }}
